
当函数或者方法执行语句出现异常时，将异常传递给函数或者方法的调用一方

如果传递到主程序，仍然没有异常处理，程序才会被终止

- 在开发中在主程序增加异常捕获
- 而在主程序中调用其他函数，只要出现异常，都会被传递到主程序的异常捕获中
- 这样就不需要在代码中，增加大量的异常捕获，能够保证代码的整洁

```py
def demo1():
    return int(input("输入整数："))

def demo2():
    return demo1()

print(demo2())
```

输入 a 报错给出的提示信息

```
输入整数：a
Traceback (most recent call last):
  File "/home/yanghao/Documents/PythonIDE/card_management/22.py", line 7, in <module>
    print(demo2())
  File "/home/yanghao/Documents/PythonIDE/card_management/22.py", line 5, in demo2
    return demo1()
  File "/home/yanghao/Documents/PythonIDE/card_management/22.py", line 2, in demo1
    return int(input("输入整数："))
ValueError: invalid literal for int() with base 10: 'a'
```

错误会一级一级的往上传递

下面修改一下代码使之能够在主程序捕获异常

```py
def demo1():
    return int(input("输入整数："))

def demo2():
    return demo1()

try:
    print(demo2())
except Exception as result:
    print("未知错误%s” % result)
```