# 什么是异常

异常定义：导致程序的正常流程被中断的事件，叫做异常

## 文件不存在异常

比如要打开d盘的LOL.exe文件，这个文件是有可能不存在的

Java中通过 new FileInputStream(f) 试图打开某文件，就有可能抛出文件不存在异常FileNotFoundException

如果不处理该异常，就会有编译错误

处理办法参见 异常处理

```java
package exception;
  
import java.io.File;
import java.io.FileInputStream;
  
public class TestException {
  
    public static void main(String[] args) {
          
        File f= new File("d:/LOL.exe");
          
        //试图打开文件LOL.exe，会抛出FileNotFoundException，如果不处理该异常，就会有编译错误
        new FileInputStream(f);
          
    }
}
```

## 异常处理

异常处理常见手段： try catch finally throws

## try catch

1. 将可能抛出FileNotFoundException 文件不存在异常的代码放在try里
2. 如果文件存在，就会顺序往下执行，并且不执行catch块中的代码
3. 如果文件不存在，try 里的代码会立即终止，程序流程会运行到对应的catch块中
4. e.printStackTrace(); 会打印出方法的调用痕迹，如此例，会打印出异常开始于TestException的第16行，这样就便于定位和分析到底哪里出了异常

```java
package date;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class TestDate {
    public static void main(String[] args) {
        File f=new File("d:/LoL.exe");
        try{
            System.out.println("Try opening LoL.exe");
            new FileInputStream(f);
            System.out.println("successfully open !");

        }catch(FileNotFoundException e){
            System.out.println("LOL.exe does not exit");
            e.printStackTrace();
        }
    }
}
```

## 使用异常的父类进行 catch

FileNotFoundException是Exception的子类，使用Exception也可以catch住FileNotFoundException

```java
package date;

import sun.reflect.annotation.ExceptionProxy;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class TestException {
    public static void main(String[] args) {
        File f=new File("d:/LOL.exe");
        try{
            System.out.println("Trying opening d:/LoL.exe");
            new FileInputStream(f);
            System.out.println("successfully !");
        }
        catch (Exception e){
            System.out.println("d:/LOL.exe");
            e.printStackTrace();
        }
    }
}
```

## 多异常捕捉办法1

有时候一段代码会抛出多种异常

```
new FileInputStream(f);
Date d=sdf.parse("2016-06-03);
```

这段代码，会抛出 文件不存在异常 FileNotFoundException 和 解析异常ParseException
解决办法之一是分别进行catch

 ```java
catch (FileNotFoundException e) {
    System.out.println("d:/LOL.exe不存在");
    e.printStackTrace();
} catch (ParseException e) {
    System.out.println("日期格式解析错误");
    e.printStackTrace();
}
 ```
```java
package date;

import sun.reflect.annotation.ExceptionProxy;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;

public class TestException {
    public static void main(String[] args) {
        File f=new File("D:/LOL.exe");
        try{
            System.out.println("Try opening file!");
            new FileInputStream(f);
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            Date d=sdf.parse("2016-06-03");
        }catch(FileNotFoundException e){
            System.out.println("File does not exit!");
            e.printStackTrace();
        }catch (ParseException e){
            System.out.println("Date format parsing error!");
            e.printStackTrace();
        }
    }
}
```

## 多异常捕捉方法2

除了分别捕捉，另一种方法就是将多个异常放到一个 catch 里统一捕捉。
```
catch (FileNotFoundException | ParseException e) 
```

这种方式从 JDK7开始支持，好处是捕捉的代码更紧凑，不足之处是，一旦发生异常，不能确定到底是哪种异常，需要通过instanceof 进行判断具体的异常类型
 ```
if (e instanceof FileNotFoundException)
	System.out.println("d:/LOL.exe不存在");
if (e instanceof ParseException)
	System.out.println("日期格式解析错误");
 ```

```java
package date;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;

public class TestException {
    public static void main(String[] args) {
        File f=new File("D:/LOL.exe");
        try{
            System.out.println("Try opening file!");
            new FileInputStream(f);
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            Date d=sdf.parse("2016-06-03");
        }catch(FileNotFoundException e|ParseException e){
            if(e instanceof FileNotFoundException){
                System.out.println("File does not exit!");
                e.printStackTrace();
            }
            if(e instanceof ParseException){
                System.out.println("Date format parsing error!");
                e.printStackTrace();
            }
        }
    }
}
```

## finally

无论是否出现异常，finally 中的代码都会执行。

```java
package date;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class TestException {
    public static void main(String[] args) {
        File f=new File("D:/LOL.exe");
        try{
            System.out.println("Try opening file!");
            new FileInputStream(f);
            System.out.println("Successfully open!");
        }catch(FileNotFoundException e){
            System.out.println("File does not exit!");
            e.printStackTrace();
        }finally {
            System.out.println("The process ends!");
        }
    }
}
```

## throws

考虑如下情况：

主方法调用 method1,method1 调用 method2,method2 中打开文件

method2中需要进行异常处理

但是 method2 不想处理，而是把这个异常通过 throws 抛出去

那么 method1 就会接到该异常。 处理办法也是两种，要么是 try catch 处理掉，要么也是抛出去。

method1 选择本地 try catch 住 一旦 try catch 住了，就相当于把这个异常消化掉了，主方法在调用 method1 的时候，就不需要进行异常处理了

```java
package date;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class TestException {
    private static void method1(){
        try{
            method2();
        }catch (FileNotFoundException e){
            e.printStackTrace();
        }
    }
    private static void method2() throws FileNotFoundException{
        File f=new File("d:/Lol.exe");
        System.out.println("Trying opening file!");
        new FileInputStream(f);
        System.out.println("successfully");
    }
    public static void main(String[] args) {
        method1();
    }
}
```

## throw和throws的区别

throws与throw这两个关键字接近，不过意义不一样，有如下区别：

1. throws 出现在方法声明上，而throw通常都出现在方法体内。
2. throws 表示出现异常的一种可能性，并不一定会发生这些异常；throw则是抛出了异常，执行throw则一定抛出了某个异常对象。